export * from './guide/guide.page';
export * from './history/history.page';
export * from './leaderboard/leaderboard.page';
export * from './statistics/statistics.page';
export * from './tokenomics/tokenomics.page';
export * from './traits/traits.page';
export * from './upgrade/upgrade.page';
export * from './games/games.page';
export * from './games/spell-seeker/spell-seeker.page';